"""Pydantic models describing the shape of user data entering and leaving the API.

Why this exists: without models, endpoints must trust whatever JSON arrives.
With models, FastAPI validates input (bad data becomes a 400 with a clear
error message), documents the shapes in /docs, and guarantees that our
functions never see malformed data.
"""

from typing import Literal

from pydantic import BaseModel, field_validator


class UserCreate(BaseModel):
    """The JSON body for POST /api/users — the fields the client controls."""

    username: str
    status: Literal["active", "disabled"] = "active"
    expire: int | None = None
    allowed_inbounds: list[str] = []
    allowed_outbounds: list[str] = []
    note: str | None = None

    @field_validator("username")
    @classmethod
    def username_is_safe(cls, value):
        """Reject usernames that would break the username@outbound email scheme.

        Why: Xray client emails are built as "username@outboundtag" and the
        routing rules match on them, so an '@' or a space inside the username
        would corrupt routing. Length is capped so emails stay sane.
        """
        value = value.strip()
        if not value:
            raise ValueError("username must not be empty")
        if "@" in value or " " in value:
            raise ValueError("username must not contain '@' or spaces")
        if len(value) > 32:
            raise ValueError("username must be at most 32 characters")
        return value


class UserUpdate(BaseModel):
    """The JSON body for PUT /api/users/{username}.

    Why every field is optional: partial update — a field that is None means
    "leave unchanged". The username is absent on purpose: it is the identity
    (the database key), so a user cannot be renamed via update.
    """

    status: Literal["active", "disabled"] | None = None
    expire: int | None = None
    allowed_inbounds: list[str] | None = None
    allowed_outbounds: list[str] | None = None
    note: str | None = None


class UserOut(BaseModel):
    """The JSON the API returns for one user.

    Why it differs from UserCreate: uuids and created_at are generated by
    the server, never sent by the client, but the admin needs to see them.
    """

    username: str
    status: str
    expire: int | None
    allowed_inbounds: list[str]
    allowed_outbounds: list[str]
    uuids: dict[str, str]
    note: str | None
    created_at: int


class ShareLink(BaseModel):
    """One generated VLESS share link."""

    inbound: str
    outbound: str
    email: str
    uri: str


class UserLinksOut(BaseModel):
    """Response for GET /api/users/{username}/links."""

    username: str
    links: list[ShareLink]
    warnings: list[str]
